// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgBase.proto

#ifndef PROTOBUF_msgBase_2eproto__INCLUDED
#define PROTOBUF_msgBase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_msgBase_2eproto();
void protobuf_AssignDesc_msgBase_2eproto();
void protobuf_ShutdownFile_msgBase_2eproto();

class ClientPacket;
class MsgHeader;

// ===================================================================

class MsgHeader : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MsgHeader) */ {
 public:
  MsgHeader();
  virtual ~MsgHeader();

  MsgHeader(const MsgHeader& from);

  inline MsgHeader& operator=(const MsgHeader& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgHeader& default_instance();

  void Swap(MsgHeader* other);

  // implements Message ----------------------------------------------

  inline MsgHeader* New() const { return New(NULL); }

  MsgHeader* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgHeader& from);
  void MergeFrom(const MsgHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgHeader* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  ::google::protobuf::int64 time() const;
  void set_time(::google::protobuf::int64 value);

  // optional int64 userid = 4;
  void clear_userid();
  static const int kUseridFieldNumber = 4;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MsgHeader)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 time_;
  ::google::protobuf::int64 userid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msgBase_2eproto();
  friend void protobuf_AssignDesc_msgBase_2eproto();
  friend void protobuf_ShutdownFile_msgBase_2eproto();

  void InitAsDefaultInstance();
  static MsgHeader* default_instance_;
};
// -------------------------------------------------------------------

class ClientPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ClientPacket) */ {
 public:
  ClientPacket();
  virtual ~ClientPacket();

  ClientPacket(const ClientPacket& from);

  inline ClientPacket& operator=(const ClientPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientPacket& default_instance();

  void Swap(ClientPacket* other);

  // implements Message ----------------------------------------------

  inline ClientPacket* New() const { return New(NULL); }

  ClientPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientPacket& from);
  void MergeFrom(const ClientPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::MsgHeader& header() const;
  ::MsgHeader* mutable_header();
  ::MsgHeader* release_header();
  void set_allocated_header(::MsgHeader* header);

  // optional bytes content = 2;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:ClientPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::MsgHeader* header_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msgBase_2eproto();
  friend void protobuf_AssignDesc_msgBase_2eproto();
  friend void protobuf_ShutdownFile_msgBase_2eproto();

  void InitAsDefaultInstance();
  static ClientPacket* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgHeader

// optional int64 time = 3;
inline void MsgHeader::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MsgHeader::time() const {
  // @@protoc_insertion_point(field_get:MsgHeader.time)
  return time_;
}
inline void MsgHeader::set_time(::google::protobuf::int64 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:MsgHeader.time)
}

// optional int64 userid = 4;
inline void MsgHeader::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MsgHeader::userid() const {
  // @@protoc_insertion_point(field_get:MsgHeader.userid)
  return userid_;
}
inline void MsgHeader::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:MsgHeader.userid)
}

// -------------------------------------------------------------------

// ClientPacket

// optional .MsgHeader header = 1;
inline bool ClientPacket::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
inline void ClientPacket::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
inline const ::MsgHeader& ClientPacket::header() const {
  // @@protoc_insertion_point(field_get:ClientPacket.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::MsgHeader* ClientPacket::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::MsgHeader;
  }
  // @@protoc_insertion_point(field_mutable:ClientPacket.header)
  return header_;
}
inline ::MsgHeader* ClientPacket::release_header() {
  // @@protoc_insertion_point(field_release:ClientPacket.header)
  
  ::MsgHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline void ClientPacket::set_allocated_header(::MsgHeader* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ClientPacket.header)
}

// optional bytes content = 2;
inline void ClientPacket::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ClientPacket::content() const {
  // @@protoc_insertion_point(field_get:ClientPacket.content)
  return content_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ClientPacket::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ClientPacket.content)
}
inline void ClientPacket::set_content(const char* value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClientPacket.content)
}
inline void ClientPacket::set_content(const void* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClientPacket.content)
}
inline ::std::string* ClientPacket::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:ClientPacket.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ClientPacket::release_content() {
  // @@protoc_insertion_point(field_release:ClientPacket.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ClientPacket::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:ClientPacket.content)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgBase_2eproto__INCLUDED
